#!/usr/bin/env bash
# Install nginx web server, and return a page when querying Nginx

apt-get update
apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.html

state=$(pgrep nginx)
if [ -n "$state" ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
