#!/usr/bin/env bash
# Install nginx web server, and return a page when querying Nginx
sudo apt-get update && upgrade
sudo apt-get install -y nginx 
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
